name: "Sync Git Repository Action"
description: "Sync a Git repository using script"
author: "Neo Chen"

inputs:
  language:
    description: "Scripting Language"
    default: "javascript"
  git_access_token:
    description: "Git Access Token for Authentication"
    required: true
  git_repo_name:
    description: "Repository Name"
    required: true
  git_branch:
    description: "Branch Name"
    required: true
  enable_git_lfs:
    description: Is enable Git LFS
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      if: ${{ inputs.language == 'javascript' }}
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Setup Python
      if: ${{ inputs.language == 'python' }}
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Run Git Repository Updater Script via JavaScript
      if: ${{ inputs.language == 'javascript' }}
      env:
        git_access_token: ${{ inputs.git_access_token }}
        git_repo_name: ${{ inputs.git_repo_name }}
        git_branch: ${{ inputs.git_branch }}
        enable_git_lfs: ${{ inputs.enable_git_lfs }}
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      run: node ${{ github.action_path }}/sync-git-repository.js
    
    - name: Run Syn Git Repository Script via Python
      if: ${{ inputs.language == 'python' }}
      env:
        git_access_token: ${{ inputs.git_access_token }}
        git_repo_name: ${{ inputs.git_repo_name }}
        git_branch: ${{ inputs.git_branch }}
        enable_git_lfs: ${{ inputs.enable_git_lfs }}
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      run: python ${{ github.action_path }}/sync_git_repository.py